# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

r:
  - oldrel
  - release

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - libmagick++-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
