# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release

os:
  - linux
  - osx
    brew_packages: imagemagick

addons:
   apt:
     packages:
      - libmagick++-dev

notifications:
  email:
    on_success: change
    on_failure: change
